import re

# List of (regular expression, replacement) pairs for abbreviations in catalan:
abbreviations_ca = [
    (re.compile("\\b%s\\." % x[0], re.IGNORECASE), x[1])
    for x in [
        ("&", "i"),
        ("@", "arrova"),
        ("A", "ampere"),
        ("B", "byte"),
        ("C", "carrer"),
        ("CIF", "codi d'identificació fiscal"),
        ("CP", "codi postal"),
        ("DEP", "descansi en pau"),
        ("DGT", "direcció general de transit"),
        ("DNI", "document nacional d'identitat"),
        ("DO", "denominació d'origen"),
        ("Dr.", "doctor"),
        ("Dra.", "doctora"),
        ("E", "est"),
        ("EUR", "euro"),
        ("Hz", "hertz"),
        ("L", "litre"),
        ("M", "mega"),
        ("MB", "megabyte"),
        ("MB/s", "megabyte per segon"),
        ("MBps", "megabyte per segon"),
        ("MHz", "megahertz"),
        ("MW", "megawatt"),
        ("MWh", "megawatt hora"),
        ("Mb", "megabit"),
        ("Mb/s", "megabit per segon"),
        ("Mbps", "megabit per segon"),
        ("M€", "milió d'euros"),
        ("N", "nord"),
        ("NE", "nord-est"),
        ("NO", "nord-oest"),
        ("O", "oest"),
        ("PTA", "pesseta"),
        ("RRHH", "recursos humans"),
        ("SA", "societat anònima"),
        ("SE", "sud-est"),
        ("SL", "societat limitada"),
        ("SO", "sud-oest"),
        ("SP", "servei públic"),
        ("Sr.", "senyor"),
        ("Sra.", "senyora"),
        ("St.", "sant"),
        ("Sta.", "santa"),
        ("TV", "televisió"),
        ("V", "volt"),
        ("VO", "versió original"),
        ("VOS", "versió original subtitulada"),
        ("Wh", "watt hora"),
        ("aC", "abans de Crist"),
        ("abr.", "abril"),
        ("abrev.", "abreviatura"),
        ("ago.", "agost"),
        ("am", "abans del migdia"),
        ("ant.", "anterior"),
        ("apmt.", "apartament"),
        ("aprox.", "aproximadament"),
        ("apt.", "apartat"),
        ("arq.", "arquitecte"),
        ("art.", "article"),
        ("atm.", "atmosfera"),
        ("aux.", "auxiliar"),
        ("av.", "avinguda"),
        ("b", "bit"),
        ("batx.", "batxillerat"),
        ("bda.", "baixada"),
        ("bl.", "bloc"),
        ("c.", "carrer"),
        ("c/", "carrer"),
        ("cal", "caloria"),
        ("cap.", "capítol"),
        ("cast.", "castellà"),
        ("cat.", "català"),
        ("cc", "centímetre cúbic"),
        ("cia.", "companyia"),
        ("cl", "centilitre"),
        ("cm", "centímetre"),
        ("col.", "columna"),
        ("com.", "comarca"),
        ("corp.", "corporació"),
        ("cró.", "carreró"),
        ("ct.", "cèntim"),
        ("ctra.", "carretera"),
        ("cènt.", "cèntim"),
        ("dC", "després de Crist"),
        ("dc", "dimecres"),
        ("dept.", "departament"),
        ("des.", "desembre"),
        ("dg", "diumenge"),
        ("dir.", "direcció"),
        ("dj", "dijous"),
        ("dl", "decilitre"),
        ("dm", "decímetre"),
        ("doc.", "document"),
        ("ds", "dissabte"),
        ("dt", "dimarts"),
        ("dte.", "descompte"),
        ("dv", "divendres"),
        ("ed.", "edició"),
        ("esc.", "escala"),
        ("esp.", "espanyol"),
        ("esq.", "esquerre/rra"),
        ("etc.", "etcètera"),
        ("ex.", "exemple"),
        ("febr.", "febrer"),
        ("fig.", "figura"),
        ("fra.", "factura"),
        ("g", "gram"),
        ("gen.", "gener"),
        ("h", "hora"),
        ("ha", "hectàrea"),
        ("inst.", "institut"),
        ("kB", "kilobyte"),
        ("kV", "kilovolt"),
        ("kW", "kilowatt"),
        ("kWh", "kilowatt hora"),
        ("kb", "kilobit"),
        ("kg", "quilogram"),
        ("km", "kilòmetre"),
        ("km/h", "kilòmetre per hora"),
        ("l", "litre"),
        ("ltda.", "limitada"),
        ("m", "metre"),
        ("m/s", "metres per segon"),
        ("mg", "mil·ligram"),
        ("min", "minut"),
        ("ml", "mil·lilitre"),
        ("mm", "mil·límetre"),
        ("màx.", "màxim"),
        ("mín.", "mínim"),
        ("n. de l'e.", "nota de l'editor"),
        ("n. de la t.", "nota de la traductora"),
        ("n. de les ed.", "nota de les editores"),
        ("n. de les t.", "nota de les traductores"),
        ("n. del t.", "nota del traductor"),
        ("n. dels ed.", "nota dels editors"),
        ("n. dels t.", "nota dels traductors"),
        ("neg.", "negatiu"),
        ("nov.", "novembre"),
        ("núm.", "número"),
        ("oct.", "octubre"),
        ("p. ex.", "per exemple"),
        ("parc.", "parcel·la"),
        ("part.", "particular"),
        ("pg.", "passeig"),
        ("pl.", "plaça"),
        ("pm", "després del migdia"),
        ("pobl.", "població"),
        ("pol.", "polígon"),
        ("pos.", "positiu"),
        ("ppal.", "principal"),
        ("prev.", "previ"),
        ("prof.", "professor"),
        ("prog.", "programa"),
        ("prov.", "província"),
        ("pta.", "pesseta"),
        ("ptes.", "pessetes"),
        ("ptge.", "passatge"),
        ("pàg.", "pàgina"),
        ("rbla.", "rambla"),
        ("ref.", "referència"),
        ("reg.", "regió"),
        ("rpm", "revolucions per minut"),
        ("rps", "revolucions per segon"),
        ("s", "segon"),
        ("s.", "segle"),
        ("s/n", "sense número"),
        ("seg.", "següent"),
        ("set.", "setembre"),
        ("sign.", "signatura"),
        ("sup.", "superior"),
        ("supl.", "suplement"),
        ("símb.", "símbol"),
        ("t", "tona"),
        ("tel.", "telèfon"),
        ("trv.", "travessia"),
        ("u.", "unitat"),
        ("urb.", "urbanització"),
        ("vol.", "volum"),
        ("vs.", "versus"),
        ("§", "epígraf"),
        ("¶", "paràgraf"),
        ("º", "grau"),
        ("ºC", "grau Celsius"),
        ("ºF", "grau Fahrenheit"),
        ("ºR", "grau Rankine"),
        ("àt.", "àtic"),
        ("íd.", "ídem"),
        ("€", "euro")
    ]
]
